version: "3.9"

services:
  app:
    build: .
    depends_on:
      - postgresDB
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
    command: npm run dev
  postgresDB:
    image: postgres:16-bullseye
    environment:
      - POSTGRES_DB=develop
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456789
    ports:
      - "5432:5432"
    volumes:
      - "postgres-db:/var/lib/postgresql/data"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=admin@admin.com'
      - 'PGADMIN_DEFAULT_PASSWORD=123456789'
    ports:
      - "5000:80"
    volumes:
      - "pgadmin-store:/var/lib/pgadmin"
    depends_on:
      - postgresDB
volumes:
  postgres-db:
  pgadmin-store: