CREATE TABLE upload (
  Subject_id INTEGER,
  Target VARCHAR(3),
  GENDER VARCHAR(1),
  AGE INTEGER,
  SMOKING INTEGER,
  YELLOW_FINGERS INTEGER,
  ANXIETY INTEGER,
  PEER_PRESSURE INTEGER,
  CHRONIC_DISEASE INTEGER,
  FATIGUE_ INTEGER,
  ALLERGY_ INTEGER,
  WHEEZING INTEGER,
  ALCOHOL_CONSUMING INTEGER,
  COUGHING INTEGER,
  BREATH_SHORTNESS INTEGER,
  SWALLOWING_DIFFICULTY INTEGER,
  CHEST_PAIN INTEGER
);
